name: Trigger auto deployment for avocadoapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/avocadoapp2-AutoDeployTrigger-303ae15d-6d69-4454-a989-380ed2276a82.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AVOCADOAPP2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AVOCADOAPP2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AVOCADOAPP2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: avocadoinc.azurecr.io
          registryUsername: ${{ secrets.AVOCADOAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AVOCADOAPP2_REGISTRY_PASSWORD }}
          containerAppName: avocadoapp2
          resourceGroup: avocadoinc
          imageToBuild: avocadoinc.azurecr.io/avocadoapp2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


