# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Docker CI

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create_env:
    runs-on: ubuntu-latest
    environment: COSI103
    
    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "123456!"
          envkey_SECRET_KEY: ${{ secrets.FDA_ID }}
          file_name: .env

  deploy_infra:
    runs-on: ubuntu-latest
    environment: COSI103

    steps:
      - uses: actions/checkout@v3
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          fda-id: ${{ secrets.FDA_ID }}
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: avocadoinc.azurecr.io
          registryUsername: ${{ secrets.AVOCADOAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AVOCADOAPP2_REGISTRY_PASSWORD }}
          containerAppName: avocadoapp2
          resourceGroup: avocadoinc
          imageToBuild: avocadoinc.azurecr.io/avocadoapp2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
