# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - run: npm ci
    - run: npm install --save-dev jest
    - run: npm install --save-dev react-test-renderer
    - run: npm install npm install --save-dev jest babel-jest @babel/preset-env @babel/preset-react react-test-renderer
    - run: npm install --save-dev @testing-library/react
    - run: npm run test

