name: Deploy Azure Container Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AVOCADOAPP3_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AVOCADOAPP3_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AVOCADOAPP3_AZURE_SUBSCRIPTION_ID }}

      - name: Get current revision
        id: get_current_revision
        run: |
          echo "Retrieving the current active revision tagged as 'current'..."
          CURRENT_REVISION=$(az containerapp revision list -n avocadoapp3 -g avocadoinc --query "[?properties.trafficWeight==\`100\`].name" -o tsv)
          if [ -z "$CURRENT_REVISION" ]; then
            echo "No current revision found."
            exit 1
          fi
          echo "CURRENT_REVISION=$CURRENT_REVISION"
          echo "CURRENT_REVISION=$CURRENT_REVISION" >> $GITHUB_ENV

      - name: Deploy new revision with 0% traffic
        run: |
          echo "Deploying new revision copied from $CURRENT_REVISION..."
          NEW_REVISION=$(az containerapp revision copy --name avocadoapp3 --resource-group avocadoinc --from-revision $CURRENT_REVISION --query "name" -o tsv)
          az containerapp ingress traffic set --name avocadoapp3 --resource-group avocadoinc --revision-weight "$NEW_REVISION=0"
          echo "NEW_REVISION=$NEW_REVISION" >> $GITHUB_ENV

      - name: Run smoke tests
        run: |
          ./run-smoke-tests.sh --revision-url ${{env.NEW_REVISION_URL}} 

      - name: Update traffic to new revision on success
        if: success()
        run: |
          az containerapp update --name avocadoapp3 --resource-group avocadoinc --traffic-weight ${{ env.NEW_REVISION }}=100

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Tests failed. Rolling back to the stable revision."
          az containerapp update --name avocadoapp3 --resource-group avocadoinc --traffic-weight ${{ env.CURRENT_REVISION }}=100
