name: Deploy Azure Container Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy new revision with 0% traffic
        run: |
          az containerapp revision copy --name myapp --resource-group myResourceGroup --from-revision ${{env.CURRENT_REVISION}} --no-wait
          az containerapp update --name myapp --resource-group myResourceGroup --traffic-weight ${NEW_REVISION}=0

      - name: Run smoke tests
        run: |
          # Replace with your method to run smoke tests
          ./run-smoke-tests.sh --revision-url ${{env.NEW_REVISION_URL}}

      - name: Update traffic to new revision on success
        if: success()
        run: |
          az containerapp update --name myapp --resource-group myResourceGroup --traffic-weight ${NEW_REVISION}=100

      - name: Rollback on failure
        if: failure()
        run: |
          # Keep the traffic at the current stable revision
          echo "Tests failed. Rolling back to the stable revision."
          az containerapp update --name myapp --resource-group myResourceGroup --traffic-weight ${CURRENT_REVISION}=100

